### ISSUE TITLE
Model screen capture with camera icon

### ISSUE THREAD

**Issue by jaub620** [Cogulator/Cogulator#26] opened 2020-06-10 18:58 UTC
First, thank you so much for this software, it is awesome! Since you have requested feedback regarding bugs I want to let you know that when the model is screen captured using the camera icon, only half of the image is captured (see image attached). Also the labels on the y-axis are blurry.

Thanks again!

![practice_gantt_chart](https://user-images.githubusercontent.com/66748235/84307431-e2301700-ab2a-11ea-8890-f3cdf79a44b6.png)

**Comment by Tapestes** [comment] 2020-06-24 00:04
Thanks for the heads-up.  Sorry it took a while to get back to you.  Can't reproduce on my mac.  I'm guessing you're on windows?  If you can confirm the operating system and version, that'd be great.  I'll fire up my windows machine and see if I can't replicate there.

**Comment by Tapestes** [comment] 2020-06-25 13:44
Unfortunately, I've not been able to replicate this issue on Windows 10 or macOS.  I'm going to close this issue for now, but if you'll reply back with the operating system on your machine, I'm happy to reopen and dig into it a bit more.

**Closed by Tapestes** 2020-06-25 13:44 UTC

**Comment by jaub620** [comment] 2020-06-30 15:32
Hi Steven,

I am using Windows 10 Pro. We were able to replicate it on other computers
running the same operating system. It's interesting you were not able to
replicate it. It's not a critical issue just something to help with
reports. We've just been screen capturing for the time being. We do have
some other usability recommendations we can suggest as well if you'd like.

Thanks again,
Julian

**Comment by Tapestes** [comment] 2020-07-01 19:04
That's curious.  Let me ping some of the folks I know are using Cogulator on Windows.  Hopefully they can find the same thing and we'll be able to debug.  If you want to send some usability recommendations, feel free.  You can email me at seste@mitre.org.
