### ISSUE TITLE
Hi, I get message about no peermissions but no permission request in System Settings

### ISSUE THREAD

**Issue by wid0ki** [Cogulator/Cogulator#33] opened 2022-05-12 13:10 UTC
<img width="317" alt="Screenshot 2022-05-12 at 15 01 44" src="https://user-images.githubusercontent.com/3679769/168082302-a573c81d-2800-4b32-9936-590345165950.png">

**Comment by Tapestes** [comment] 2022-05-16 14:27
Looks like this might be a new issue with a recent MacOS update.  I'm able to reproduce, but in spite of the error message, the folder and files get created and are accessible.  If you do not see an Examples folder in Cogulator, let me know.  We're working on a new, lighter release and we'll make sure this bug is addressed there.

**Comment by Tapestes** [comment] 2022-06-29 03:21
Issue should be resolved in the latest release, which is v4.3.7. 
[https://github.com/Cogulator/Cogulator/releases/tag/v4.3.7](https://github.com/Cogulator/Cogulator/releases/tag/v4.3.7).
Heads-up: as of the latest release, folks on Mac will have to make sure they grab the version appropriate for their machine (old school Apple Intel or new school Apple Silicon/M1).

**Closed by Tapestes** 2022-06-29 03:21 UTC
